# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: 🙋  Usage Questions
  url: https://github.com/conda-forge-warning/discussions
  about: |
    Use Conda-Forge Warning's GitHub Discussions to ask "How do I do X with Cookiecutter?".
- name: 📖  Tutorial
  url: https://github.com/conda-forge-warning
  about: |
    The Conda-Forge Warning tutorial is continually updated and provides an in depth walkthrough
    of how to use the latest release of Cookiecutter.
- name: 📝  Conda-Forge Warning Code of Conduct
  url: https://github.com/conda-forge-warning/coc/CODE_OF_CONDUCT.md
  about: Expectations for how people will interact with each other on Cookiecutter's GitHub.
